Fix empty config crash
Steps to reproduce:

```
sfctl time init
sfctl time sync
```

Actual result:

```
     NoMethodError:
       undefined method `length' for nil:NilClass
     # ./lib/sfctl/commands/time/sync.rb:24:in `execute'
     # ./spec/unit/time/sync_spec.rb:202:in `block (2 levels) in <top (required)>'
```

Expected result:

Error message "Please add a connection before continue."